# Generated by Django 4.2.3 on 2023-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="products",
            field=models.ManyToManyField(to="home.product"),
        ),
    ]
